# < List Comprehension >   
- list comprehension 사용한 경우를 일반 문과 비교하면 처리속도 우세함

In [8]:
result = []

for i in range(10):
    result.append(i)

print(result)
print()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]



In [6]:
result2 = [i for i in range(10)]
print(result2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


- List Comprehension   
result와 result2 결과는 같지만 실행 속도 우세     

      
   

### List Comprehension if문   
- 순서   
1. 변수, 변수 범위, if문   
2. 변수, if문, else문, 변수 범위

In [9]:
result = []

for i in range(10):
    if i % 2 == 0:
        result.append(i)

print(result)
print()

[0, 2, 4, 6, 8]



In [5]:
# 순서 1.변수, 변수 범위, if문
result2 = [i for i in range(10) if i % 2 == 0]
print(result2)

[0, 2, 4, 6, 8]


In [6]:
result = []

for i in range(10):
    if i % 2 == 0:
        result.append(i)
    else:
        result.append(99)

print(result)
print()

[0, 99, 2, 99, 4, 99, 6, 99, 8, 99]



In [7]:
# 순서 2.변수, if문, else문, 변수 범위
result2 = [i  if i % 2 == 0 else 99 for i in range(10)]
print(result2)

[0, 99, 2, 99, 4, 99, 6, 99, 8, 99]


      
### List Comprehension 이중 for문

In [18]:
result = []
case1 = ["A", "B", "C"]
case2 = ["A", "B", "C"]
for i in case1:
    for j in case2:
        result.append(i + j)
print(result)

['AA', 'AB', 'AC', 'BA', 'BB', 'BC', 'CA', 'CB', 'CC']


In [20]:
result2 = [i + j for i in case1 for j in case2]
print(result2)

['AA', 'AB', 'AC', 'BA', 'BB', 'BC', 'CA', 'CB', 'CC']


#### List Comprehension 이중 for문 + if문

In [22]:
result2 = [i + j for i in case1 for j in case2 if i != j ]
print(result2)

['AB', 'AC', 'BA', 'BC', 'CA', 'CB']


* Python은 list에 여러 타입 넣을 수 있음(속도느림)   
* numpy list는 다른 타입 못 넣음(속도빠름)

# < Numpy >
- Python -  list에 여러 타입(shape) 넣을 수 있음 (속도느림)
- Numpy - list에 한 타입만 넣을 수 있음 (속도빠름)
   
- 결과상 python list는 "," 있고, numpy list는 "," 없다

In [11]:
import numpy as np

- 향후 numpy 함수 사용할 때 np.

In [12]:
a1 = np.array([0,1,2,3,4,5])
print(a1)

[0 1 2 3 4 5]


In [13]:
print(type(a1))  # type 확인

<class 'numpy.ndarray'>


In [15]:
print(a1.dtype)  # 배열 항목의 속성 확인

int32


In [19]:
list1 = [[1,2,3], [4,5,6], [7,8,9]]
print(list1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


└> python 2차원 배열

In [20]:
list2 = np.array(list1)
print(list2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


└> numpy 2차원 배열

### np.arange   
- numpy 배열 생성시 사용
- np.arange(a,b,c) : a ~ b-1 중 c간격으로   
- np.arange(a,b,c).reshape(x,y) : 위의 결과를 x*y matrix로   
   * ab = xy 주의  (ab != xy 에러)
   * x = -1 or y = -1 : x = -1 → x = ab/y  (y = -1 경우도 같은 원리)

In [21]:
a = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


In [22]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
a = np.arange(1, 10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [24]:
a = np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [25]:
a = np.arange(12).reshape(4,-1)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [26]:
a = np.arange(12).reshape(-1,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [27]:
a = np.arange(11).reshape(-1,3)
print(a)

ValueError: cannot reshape array of size 11 into shape (3)

### np.linspace   
- np.linspace(a, b, c) : a ~ b-1 중 c등분
- 숫자. : 실수 의미   
- zeros, ones, eye
- element-wise operation

In [40]:
a = np.linspace(1, 10, 10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [41]:
a = np.linspace(1, 10, 8)
print(a)

[ 1.          2.28571429  3.57142857  4.85714286  6.14285714  7.42857143
  8.71428571 10.        ]


In [42]:
a = np.linspace(0, np.pi, 20)
print(a)

[0.         0.16534698 0.33069396 0.49604095 0.66138793 0.82673491
 0.99208189 1.15742887 1.32277585 1.48812284 1.65346982 1.8188168
 1.98416378 2.14951076 2.31485774 2.48020473 2.64555171 2.81089869
 2.97624567 3.14159265]


In [43]:
a1 = np.zeros(10, int)
print(a1)
a2 = np.zeros((3, 4), int)
print(a2)
a3 = np.ones(5)
print(a3)
a4 = np.ones((3, 5))
print(a4)
a5 = np.eye(3)
print(a5)

[0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


- 숫자 타입 지정하지 않으면 실수(기본)
- matrix 크기 지정 가능   
   
- zeros : 0으로 채워진 배열   
- ones :  1으로 채워진 배열   
- eye : 단위행렬

In [28]:
list1 = [10, 20, 30, 40]
list2 = [1, 2, 3, 4]
print(list1 + list2)

[10, 20, 30, 40, 1, 2, 3, 4]


In [29]:
import numpy as np
a1 = np.array(list1)
a2 = np.array(list2)
print(a1 + a2)

[11 22 33 44]


In [30]:
print(a1 > a2)

[ True  True  True  True]


- element-wise operation   
python과 다르게 numpy는 항목끼리 사칙연산과 비교 가능   
단, 두 항목은 shape 동일해야함

In [47]:
a1 = np.arange(1, 6)

print(a1.sum())
print(a1.mean())
print(a1.std())
print(a1.var())
print(a1.min())
print(a1.max())
print(a1.cumsum())
print(a1.cumprod())

15
3.0
1.4142135623730951
2.0
1
5
[ 1  3  6 10 15]
[  1   2   6  24 120]


- cumsum : 누적 합
- cumprod : 누적 곱

In [48]:
a = np.array([0, 1, 2, 3]).reshape(2, 2)
print(a)

b = np.array([3, 2, 0, 1]).reshape(2, 2)
print(b)
print('-'*20)
print(a.dot(b)) # 행렬곱
print(np.dot(a, b)) # 행렬곱
print('-'*20)
print(np.transpose(a)) # 전치행렬
print(a.transpose()) # 전치행렬
print(a.T) # 전치행렬
print('-'*20)
print(np.linalg.inv(a)) # 역행렬
print(np.linalg.det(a)) # 행렬식

[[0 1]
 [2 3]]
[[3 2]
 [0 1]]
--------------------
[[0 1]
 [6 7]]
[[0 1]
 [6 7]]
--------------------
[[0 2]
 [1 3]]
[[0 2]
 [1 3]]
[[0 2]
 [1 3]]
--------------------
[[-1.5  0.5]
 [ 1.   0. ]]
-2.0


- numpy는 선형대수 지원

In [49]:
a = np.array([0, 10, 20, 30, 40, 50])

print(a[[1, 3, 4]])

b = np.arange(10, 100, 10).reshape(3, 3)
print(b)
print(b[0, 2])
b[2, 2] = 97
print(b)
print(b[1])
print('-'*20)
b[1] = np.array([45, 55, 65])
print(b)
b[2] = [75, 85, 95]
print(b)
print('-'*20)
print(b[[0, 2], [0, 1]])

[10 30 40]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
30
[[10 20 30]
 [40 50 60]
 [70 80 97]]
[40 50 60]
--------------------
[[10 20 30]
 [45 55 65]
 [70 80 97]]
[[10 20 30]
 [45 55 65]
 [75 85 95]]
--------------------
[10 85]


- b[[0, 2], [0, 1]]   
[0, 0] = 10   
[2, 1] = 85   
[10, 85]

In [50]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a[a > 3])
print(a[(a % 2) == 0])

[4 5 6]
[2 4 6]


- [] 안에 식을 지원함

In [31]:
a = np.array([0, 10, 20, 30, 40, 50])
print(a[1:4])
print(a[:3])
print(a[2:])
a[2:5] = np.array([25, 35, 45])
print(a)

[10 20 30]
[ 0 10 20]
[20 30 40 50]
[ 0 10 25 35 45 50]


In [32]:
a = np.arange(10, 100, 10).reshape(3, 3)
print(a)
print(a[1:3, 1:3])
print(a[:3, 1:])
print(a[1][0:2])
a[0:2, 1:3] = np.array([[25, 35], [55, 65]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[50 60]
 [80 90]]
[[20 30]
 [50 60]
 [80 90]]
[40 50]
[[10 25 35]
 [40 55 65]
 [70 80 90]]
