In [1]:
import pandas as pd

## PANDAS Series
- index와 value 지원
- value만 뽑을시 numpy로 출력
- 여러 shape 지원

In [2]:
s1 = pd.Series([10, 20, 30, 40, 50])
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [3]:
print(s1.index)

RangeIndex(start=0, stop=5, step=1)


In [4]:
print(s1.values)

[10 20 30 40 50]


In [5]:
print(type(s1.values))

<class 'numpy.ndarray'>


In [6]:
s2 = pd.Series(['a', 'b', 'c', 1, 2, 3])
print(s2)

0    a
1    b
2    c
3    1
4    2
5    3
dtype: object


In [8]:
import numpy as np
s3 = pd.Series([np.nan, 1, 2])
print(s3)

0    NaN
1    1.0
2    2.0
dtype: float64


- nan not a number; null(numpy 지원)

In [9]:
index_date = ['2020-03-20', '2020-03-21', '2020-03-22', '2020-03-23']
s4 = pd.Series([200, 187, np.nan, 210], index=index_date)
print(s4)

2020-03-20    200.0
2020-03-21    187.0
2020-03-22      NaN
2020-03-23    210.0
dtype: float64


- index 타입 지정 가능

In [11]:
s5 = pd.Series({'국어':100, '영어':95, '수학':100})
print(s5)

국어    100
영어     95
수학    100
dtype: int64


In [12]:
p = pd.date_range(start='2020-01-20', end='2020-01-27')
print(p)

DatetimeIndex(['2020-01-20', '2020-01-21', '2020-01-22', '2020-01-23',
               '2020-01-24', '2020-01-25', '2020-01-26', '2020-01-27'],
              dtype='datetime64[ns]', freq='D')


- datetime 지원(pandas)

In [13]:
p = pd.date_range(start='2020/01/20', end='2020.01.27')
print(p)

DatetimeIndex(['2020-01-20', '2020-01-21', '2020-01-22', '2020-01-23',
               '2020-01-24', '2020-01-25', '2020-01-26', '2020-01-27'],
              dtype='datetime64[ns]', freq='D')


결과는 항상 .으로

In [14]:
p = pd.date_range(start='2020-05-01', periods=7)
print(p)

DatetimeIndex(['2020-05-01', '2020-05-02', '2020-05-03', '2020-05-04',
               '2020-05-05', '2020-05-06', '2020-05-07'],
              dtype='datetime64[ns]', freq='D')


frequenct option: D(day) / W(week; 일요일이 시작)

In [15]:
p = pd.date_range(start='2020-01-01', periods=4, freq='2D')
print(p)

DatetimeIndex(['2020-01-01', '2020-01-03', '2020-01-05', '2020-01-07'], dtype='datetime64[ns]', freq='2D')


In [17]:
p = pd.date_range(start='2022-01-01', periods=5, freq='W')
print(p)

DatetimeIndex(['2022-01-02', '2022-01-09', '2022-01-16', '2022-01-23',
               '2022-01-30'],
              dtype='datetime64[ns]', freq='W-SUN')


In [18]:
p = pd.date_range(start='2022-01-01', periods=5, freq='W-MON')
print(p)

DatetimeIndex(['2022-01-03', '2022-01-10', '2022-01-17', '2022-01-24',
               '2022-01-31'],
              dtype='datetime64[ns]', freq='W-MON')


-  freq='W-MON'; 월요일부터 시작해서 5개 출력

In [19]:
p = pd.date_range(start='2023-02-01', periods=12, freq='2M')
print(p)

DatetimeIndex(['2023-02-28', '2023-04-30', '2023-06-30', '2023-08-31',
               '2023-10-31', '2023-12-31', '2024-02-29', '2024-04-30',
               '2024-06-30', '2024-08-31', '2024-10-31', '2024-12-31'],
              dtype='datetime64[ns]', freq='2M')


freq='2M'; 해당 월 마지막 일부터 2달씩

In [20]:
p = pd.date_range(start='2023-02-01', periods=12, freq='2BM')
print(p)

DatetimeIndex(['2023-02-28', '2023-04-28', '2023-06-30', '2023-08-31',
               '2023-10-31', '2023-12-29', '2024-02-29', '2024-04-30',
               '2024-06-28', '2024-08-30', '2024-10-31', '2024-12-31'],
              dtype='datetime64[ns]', freq='2BM')


freq='2BM'; business month; 2달씩, 마지막 검정날

In [23]:
p = pd.date_range(start='2023-01-03', periods=4, freq='QS')
print(p)

DatetimeIndex(['2023-04-01', '2023-07-01', '2023-10-01', '2024-01-01'], dtype='datetime64[ns]', freq='QS-JAN')


freq='QS': quarter start day

In [24]:
p = pd.date_range(start='2020-01-01 08:00', periods=10, freq='H')
print(p)

DatetimeIndex(['2020-01-01 08:00:00', '2020-01-01 09:00:00',
               '2020-01-01 10:00:00', '2020-01-01 11:00:00',
               '2020-01-01 12:00:00', '2020-01-01 13:00:00',
               '2020-01-01 14:00:00', '2020-01-01 15:00:00',
               '2020-01-01 16:00:00', '2020-01-01 17:00:00'],
              dtype='datetime64[ns]', freq='H')


## PANDAS DataFrame

In [25]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(df)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9


index name, column name

In [26]:
print(df.values)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
index_date = pd.date_range('2020-05-01', periods=4)
columns_list = ['A', 'B', 'C']
df = pd.DataFrame(data, index=index_date, columns=columns_list)
print(df)

             A   B   C
2020-05-01   1   2   3
2020-05-02   4   5   6
2020-05-03   7   8   9
2020-05-04  10  11  12


In [29]:
data = {'연도': [2015, 2016, 2016, 2017, 2017],
        '지사': ['서울', '서울', '부산', '서울', '부산'],
        '고객 수': [200, 250, 150, 300, 200]}
df = pd.DataFrame(data)
print(df)

     연도  지사  고객 수
0  2015  서울   200
1  2016  서울   250
2  2016  부산   150
3  2017  서울   300
4  2017  부산   200


dictionary 타입으로 주면   
key - column name

In [30]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])
print(s1 + s2)
print(s2 - s1)
print(s1 * s2)
print(s2 / s1)

0    11
1    22
2    33
3    44
4    55
dtype: int64
0     9
1    18
2    27
3    36
4    45
dtype: int64
0     10
1     40
2     90
3    160
4    250
dtype: int64
0    10.0
1    10.0
2    10.0
3    10.0
4    10.0
dtype: float64


numpy와 pandas 차이점   
shape 달라도 지원   
계산 못하면 nan

In [31]:
s3 = pd.Series([1, 2, 3, 4])
s4 = pd.Series([10, 20, 30, 40, 50])
print(s3 + s4)

0    11.0
1    22.0
2    33.0
3    44.0
4     NaN
dtype: float64


In [32]:
data1 = {'A': [1, 2, 3, 4, 5],
         'B': [10, 20, 30, 40, 50],
         'C': [100, 200, 300, 400, 500]}
df1 = pd.DataFrame(data1)
print(df1)

data2 = {'A': [6, 7, 8],
         'B': [60, 70, 80],
         'C': [600, 700, 800]}
df2 = pd.DataFrame(data2)
print(df2)
print('='*20)
print(df1 + df2)

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500
   A   B    C
0  6  60  600
1  7  70  700
2  8  80  800
      A      B       C
0   7.0   70.0   700.0
1   9.0   90.0   900.0
2  11.0  110.0  1100.0
3   NaN    NaN     NaN
4   NaN    NaN     NaN


int default ; 32int   
float default; 64float

In [35]:
table_data3 = {'봄':  [256.5, 264.3, 215.9, 223.2, 312.8],
              '여름': [770.6, 567.5, 599.8, 387.1, 446.2],
              '가을': [363.5, 231.2, 293.1, 247.7, 381.6],
              '겨울': [139.3, 59.9, 76.9, 109.1, 108.1]}
columns_list = ['봄', '여름', '가을', '겨울']  # column 순서 정해줌
index_list = ['2012', '2013', '2014', '2015', '2016']

df3 = pd.DataFrame(table_data3, columns = columns_list, index = index_list)
print(df3)
print('='*30)
print(df3.mean()) # 계절별  [5][4]로 생각
print('='*30)
print(df3.std())  # 계절별
print('='*30)
print(df3.mean(axis=1)) # 연도별
print('='*30)
print(df3.std(axis=1)) # 연도별
print('='*30)
print(df3.describe())

          봄     여름     가을     겨울
2012  256.5  770.6  363.5  139.3
2013  264.3  567.5  231.2   59.9
2014  215.9  599.8  293.1   76.9
2015  223.2  387.1  247.7  109.1
2016  312.8  446.2  381.6  108.1
봄     254.54
여름    554.24
가을    303.42
겨울     98.66
dtype: float64
봄      38.628267
여름    148.888895
가을     67.358496
겨울     30.925523
dtype: float64
2012    382.475
2013    280.725
2014    296.425
2015    241.775
2016    312.175
dtype: float64
2012    274.472128
2013    211.128782
2014    221.150739
2015    114.166760
2016    146.548658
dtype: float64
                봄          여름          가을          겨울
count    5.000000    5.000000    5.000000    5.000000
mean   254.540000  554.240000  303.420000   98.660000
std     38.628267  148.888895   67.358496   30.925523
min    215.900000  387.100000  231.200000   59.900000
25%    223.200000  446.200000  247.700000   76.900000
50%    256.500000  567.500000  293.100000  108.100000
75%    264.300000  599.800000  363.500000  109.100000
max    312.8000

df3.mean(axis=0) ; 디폴트; column 평균   
df3.mean(axis=1) ; 